### PR TITLE
Webpack config

### PR DESCRIPTION
**Pull request by ttreit**
Just the most basic webpack config to get started

### CODE REVIEW

**Comment by rvrita** [comment]
This looks good, are you adding the babel-loader with a separate PR (to the rules section in your webpack config)? 
The output file name should be bundle.js.

**Comment by ttreit** [comment]
> This looks good, are you adding the babel-loader with a separate PR (to the rules section in your webpack config)?
> The output file name should be bundle.js.

This is just my initial basic config - I'll be adding to it as I go forward, yes. Not sure yet what all will be included, babel almost certainly will be added, though technically I think you could use babel separately if you really wanted to.

**Comment by rvrita** [comment]
Webpack can't transpile ES6 to ES5 without configuring it with some 'loaders', need to use babel-loader and some presets to do it for you.( But you can have a babel config too.) I'm sure you'll figure it out but LMK if you need help.

**Comment by ttreit** [comment]
> Webpack can't transpile ES6 to ES5 without configuring it with some 'loaders', need to use babel-loader and some presets to do it for you.( But you can have a babel config too.) I'm sure you'll figure it out but LMK if you need help.

Yeah I think having webpack do it makes the most sense but I'm pretty sure you could transpile manually with babel and then run webpack (I don't know why you would). I've used webpack a little (experimenting) without babel. But the bottom line is my plan is to use babel anyways, just havent gotten there yet.  :)

**Comment by ttreit** [comment]
> This looks good, are you adding the babel-loader with a separate PR (to the rules section in your webpack config)?
> The output file name should be bundle.js.

Curious - why do you say the output file should be bundle.js?

**Pull request merged**
